# Generated by Django 5.0.6 on 2024-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_class_loginuser_studentattendance_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
