# Generated by Django 5.0.6 on 2024-07-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
