# Generated by Django 5.0.6 on 2024-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='sclass',
            field=models.CharField(default='', max_length=20),
        ),
    ]
