# Generated by Django 5.0.6 on 2024-07-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_studentattendance_studentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('subjec', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('enquiry_date', models.CharField(max_length=25)),
            ],
        ),
    ]
