# Generated by Django 5.0.6 on 2024-07-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='message',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='subjec',
            new_name='pname',
        ),
    ]
